name: 'Golang CI Action'
description: 'Action that executes common CI steps for Go project'
author: 'epavlova'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'smile'
  color: 'yellow'
